### ISSUE TITLE
Make heatmap visualisation of traits per family fit in pipeline

### ISSUE THREAD

**Issue by nickynicolson** [KewBridge/tropical-plant-id-myrtales#11]
We have a script to build the heatmap here: https://github.com/KewBridge/tropical-plant-id-myrtales/blob/main/heatmaps_and_stats.py

To fit it into the pipeline, we need to do these steps:

- [x] Edit `heatmaps_and_stats.py` - modify it so that the chart is written to an image file rather than shown (using `plt.savefig(filename)` rather than `plt.show()`)
- [x] Edit `heatmaps_and_stats.py` script - modify it so that it accepts command line arguments - these will be the input data file (data/families.csv) and the output filename(s). Have a look at any of the other scripts in the pipeline for examples (eg https://github.com/KewBridge/tropical-plant-id-myrtales/blob/main/cleanbookmarks.py) as an example. To do this in the heatmap script you need to:
    - [x] Import the argparse library (`import argparse`)
    - [x] Define a `main()` method and set up the argument parser. All your existing code will fit in here, instead of using your hardcoded filenames, you'll read these from the argument parser (e.g. `args.input_filename`, `args.output_chart_filename`)
    - [x] Add the code to call the main method when the script is executed:
        ```python
            if __name__ == "__main__":
                main()
        ```
- [x] Edit `Makefile` to add a target to make your chart:
    ```make
        data/heatmap.png: heatmaps_and_stats.py data/families.csv
            python $^ $@

    ```

You should now be able to do `make data/heatmap.png` on your local machine and see the code run to build the output. These last steps get it all running via github actions too:

- [x] Edit the github actions file (`/.github/workflows/makefile.yml`) to make your chart: after the step named "download images" add:
    ```yaml
    - name: Build heatmap chart
      run: make data/heatmap.png
    ```
- [x] Edit the github actions workflow file to attach your chart image to the run: at the very end of the workflow, after the step named "Attach built artifact (gbif_download.bib) to run", add:
    ```yaml
    - name: Attach built artifact (heatmap.png) to run 
        if: ${{ github.event_name == 'workflow_dispatch'}}
        uses: actions/upload-artifact@v4
        with:
            name: heatmap.png
            path: data/heatmap.png        
    ```
